export const TOOL_ROUTES = [
  '/crypto/aes',
  '/crypto/jwt',
  '/hash/md5',
  '/hash/sha2',
  '/hash/sha3',
  '/hash/blake',
  '/hash/xxhash3',
  '/performance/cpu-benchmark',
  '/encoding/base64',
  '/encoding/base64-image',
  '/encoding/base58',
  '/encoding/qrcode',
  '/encoding/qrcode-decode',
  '/encoding/url',
  '/text/diff',
  '/text/json-format',
  '/text/string-length',
  '/text/timestamp',
  '/text/regex',
  '/text/id-card',
  '/text/name-risk',
  '/security/password-strength',
  '/finance/social-insurance',
  '/finance/flexible-insurance',
  '/finance/beijing-getihu',
  '/finance/restaurant-breakeven',
  '/sql/supabase-rls',
  '/design/color',
  '/random/uuid',
  '/random/string',
  '/random/ugly-avatar',
  '/bp/jwt',
  '/bp/sign',
  '/image/exif',
  '/image/heic',
  '/security/sensitive-masker',
  '/security/china-user-detector',
  '/file/zip-inspector',
  '/image/ocr',
  '/image/compress',
  '/image/crop',
  '/text/wordbook',
  '/text/markdown-to-html',
  // '/image/bg-remove', // disabled: WASM inference unstable across devices
] as const

export type ToolRoute = (typeof TOOL_ROUTES)[number]
