import {
  Lock,
  Hash,
  Binary,
  Layers,
  Zap,
  Cpu,
  FileCode,
  QrCode,
  Type,
  ArrowLeftRight,
  Braces,
  Smile,
  KeyRound,
  ShieldCheck,
  Clock,
  Link,
  KeySquare,
  Terminal,
  Palette,
  Regex,
  IdCard,
  Fingerprint,
  DatabaseZap,
  Camera,
  FileImage,
  EyeOff,
  FileArchive,
  ScanText,
  Baby,
  Wallet,
  Briefcase,
  Store,
  Shuffle,
  Minimize2,
  Crop,
  BookOpen,
  UtensilsCrossed,
  Radar,
  // Scissors, // bg-remove disabled
  type LucideIcon,
} from 'lucide-react'
import { type ToolRoute } from '@/lib/routes'

export interface ToolConfig {
  id: string
  descriptionKey: string
  href: ToolRoute
  icon: LucideIcon
  category: ToolCategory
}

export type ToolCategory = 'Cryptography' | 'Security' | 'Hash' | 'Performance' | 'Encoding' | 'Text' | 'Random' | 'Fun' | 'BP Authentication' | 'Design' | 'SQL' | 'Image' | 'File' | 'Finance'

export const TOOLS: ToolConfig[] = [
  {
    id: 'aes',
    descriptionKey: 'aes.description',
    href: '/crypto/aes',
    icon: Lock,
    category: 'Cryptography',
  },
  {
    id: 'jwt-decode',
    descriptionKey: 'jwt-decode.description',
    href: '/crypto/jwt',
    icon: KeySquare,
    category: 'Cryptography',
  },
  {
    id: 'ssh-keygen',
    descriptionKey: 'ssh-keygen.description',
    href: '/crypto/ssh-keygen',
    icon: Terminal,
    category: 'Cryptography',
  },
  {
    id: 'md5',
    descriptionKey: 'md5.description',
    href: '/hash/md5',
    icon: Hash,
    category: 'Hash',
  },
  {
    id: 'sha2',
    descriptionKey: 'sha2.description',
    href: '/hash/sha2',
    icon: Binary,
    category: 'Hash',
  },
  {
    id: 'sha3',
    descriptionKey: 'sha3.description',
    href: '/hash/sha3',
    icon: Layers,
    category: 'Hash',
  },
  {
    id: 'blake',
    descriptionKey: 'blake.description',
    href: '/hash/blake',
    icon: Zap,
    category: 'Hash',
  },
  {
    id: 'xxhash3',
    descriptionKey: 'xxhash3.description',
    href: '/hash/xxhash3',
    icon: Cpu,
    category: 'Hash',
  },
  {
    id: 'cpu-benchmark',
    descriptionKey: 'cpu-benchmark.description',
    href: '/performance/cpu-benchmark',
    icon: Cpu,
    category: 'Performance',
  },
  {
    id: 'base64',
    descriptionKey: 'base64.description',
    href: '/encoding/base64',
    icon: FileCode,
    category: 'Encoding',
  },
  {
    id: 'base64-image',
    descriptionKey: 'base64-image.description',
    href: '/encoding/base64-image',
    icon: FileCode,
    category: 'Encoding',
  },
  {
    id: 'base58',
    descriptionKey: 'base58.description',
    href: '/encoding/base58',
    icon: FileCode,
    category: 'Encoding',
  },
  {
    id: 'qrcode',
    descriptionKey: 'qrcode.description',
    href: '/encoding/qrcode',
    icon: QrCode,
    category: 'Encoding',
  },
  {
    id: 'qrcode-decode',
    descriptionKey: 'qrcode-decode.description',
    href: '/encoding/qrcode-decode',
    icon: QrCode,
    category: 'Encoding',
  },
  {
    id: 'url-encode',
    descriptionKey: 'url-encode.description',
    href: '/encoding/url',
    icon: Link,
    category: 'Encoding',
  },
  {
    id: 'text-diff',
    descriptionKey: 'text-diff.description',
    href: '/text/diff',
    icon: ArrowLeftRight,
    category: 'Text',
  },
  {
    id: 'json-format',
    descriptionKey: 'json-format.description',
    href: '/text/json-format',
    icon: Braces,
    category: 'Text',
  },
  {
    id: 'string-length',
    descriptionKey: 'string-length.description',
    href: '/text/string-length',
    icon: Type,
    category: 'Text',
  },
  {
    id: 'timestamp',
    descriptionKey: 'timestamp.description',
    href: '/text/timestamp',
    icon: Clock,
    category: 'Text',
  },
  {
    id: 'regex',
    descriptionKey: 'regex.description',
    href: '/text/regex',
    icon: Regex,
    category: 'Text',
  },
  {
    id: 'id-card',
    descriptionKey: 'id-card.description',
    href: '/text/id-card',
    icon: IdCard,
    category: 'Text',
  },
  {
    id: 'name-risk',
    descriptionKey: 'name-risk.description',
    href: '/text/name-risk',
    icon: Baby,
    category: 'Text',
  },
  {
    id: 'payroll-cn',
    descriptionKey: 'payroll-cn.description',
    href: '/finance/social-insurance',
    icon: Wallet,
    category: 'Finance',
  },
  {
    id: 'flexible-insurance',
    descriptionKey: 'flexible-insurance.description',
    href: '/finance/flexible-insurance',
    icon: Briefcase,
    category: 'Finance',
  },
  {
    id: 'beijing-getihu',
    descriptionKey: 'beijing-getihu.description',
    href: '/finance/beijing-getihu',
    icon: Store,
    category: 'Finance',
  },
  {
    id: 'restaurant-breakeven',
    descriptionKey: 'restaurant-breakeven.description',
    href: '/finance/restaurant-breakeven',
    icon: UtensilsCrossed,
    category: 'Finance',
  },
  {
    id: 'password-strength',
    descriptionKey: 'password-strength.description',
    href: '/security/password-strength',
    icon: ShieldCheck,
    category: 'Security',
  },
  {
    id: 'sensitive-masker',
    descriptionKey: 'sensitive-masker.description',
    href: '/security/sensitive-masker',
    icon: EyeOff,
    category: 'Security',
  },
  {
    id: 'china-user-detector',
    descriptionKey: 'china-user-detector.description',
    href: '/security/china-user-detector',
    icon: Radar,
    category: 'Security',
  },
  {
    id: 'supabase-rls',
    descriptionKey: 'supabase-rls.description',
    href: '/sql/supabase-rls',
    icon: DatabaseZap,
    category: 'SQL',
  },
  {
    id: 'color',
    descriptionKey: 'color.description',
    href: '/design/color',
    icon: Palette,
    category: 'Design',
  },
  {
    id: 'uuid',
    descriptionKey: 'uuid.description',
    href: '/random/uuid',
    icon: Fingerprint,
    category: 'Random',
  },
  {
    id: 'random-string',
    descriptionKey: 'random-string.description',
    href: '/random/string',
    icon: Shuffle,
    category: 'Random',
  },
  {
    id: 'ugly-avatar',
    descriptionKey: 'ugly-avatar.description',
    href: '/random/ugly-avatar',
    icon: Smile,
    category: 'Random',
  },
  {
    id: 'birthplace-simulator',
    descriptionKey: 'birthSimulator.description',
    href: '/fun/birthplace-simulator',
    icon: Baby,
    category: 'Fun',
  },
  {
    id: 'bp-jwt',
    descriptionKey: 'bp-jwt.description',
    href: '/bp/jwt',
    icon: KeyRound,
    category: 'BP Authentication',
  },
  {
    id: 'bp-sign',
    descriptionKey: 'bp-sign.description',
    href: '/bp/sign',
    icon: ShieldCheck,
    category: 'BP Authentication',
  },
  {
    id: 'zip-inspector',
    descriptionKey: 'zip-inspector.description',
    href: '/file/zip-inspector',
    icon: FileArchive,
    category: 'File',
  },
  {
    id: 'exif',
    descriptionKey: 'exif.description',
    href: '/image/exif',
    icon: Camera,
    category: 'Image',
  },
  {
    id: 'heic',
    descriptionKey: 'heic.description',
    href: '/image/heic',
    icon: FileImage,
    category: 'Image',
  },
  {
    id: 'ocr',
    descriptionKey: 'ocr.description',
    href: '/image/ocr',
    icon: ScanText,
    category: 'Image',
  },
  {
    id: 'img-compress',
    descriptionKey: 'img-compress.description',
    href: '/image/compress',
    icon: Minimize2,
    category: 'Image',
  },
  {
    id: 'img-crop',
    descriptionKey: 'img-crop.description',
    href: '/image/crop',
    icon: Crop,
    category: 'Image',
  },
  {
    id: 'wordbook',
    descriptionKey: 'wordbook.description',
    href: '/text/wordbook',
    icon: BookOpen,
    category: 'Text',
  },
  {
    id: 'markdown-to-html',
    descriptionKey: 'markdown-to-html.description',
    href: '/text/markdown-to-html',
    icon: FileCode,
    category: 'Text',
  },
  // {
  //   id: 'bg-remove',
  //   descriptionKey: 'bg-remove.description',
  //   href: '/image/bg-remove',
  //   icon: Scissors,
  //   category: 'Image',
  // },
]

export const CATEGORIES: ToolCategory[] = ['Encoding', 'Hash', 'Performance', 'Cryptography', 'Text', 'SQL', 'Security', 'Finance', 'Random', 'Fun', 'Design', 'Image', 'File', 'BP Authentication']

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOLS.filter((t) => t.category === category)
}
